/* Default config.h generated by Makefile */
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif
#define HAVE_LIBBZ2 1
#define HAVE_LIBLZMA 1
#ifndef __APPLE__
#define HAVE_LZMA_H 1
#endif
#define HAVE_DRAND48 1
#define HAVE_LIBCURL 1
#if defined __x86_64__ || defined __arm__ || defined __aarch64__
#define HAVE_ATTRIBUTE_CONSTRUCTOR 1
#endif
#if (defined(__x86_64__) || defined(_M_X64))
#define HAVE_ATTRIBUTE_TARGET 1
#define HAVE_BUILTIN_CPU_SUPPORT_SSSE3 1
#endif
