# Default htscodecs.mk generated by Makefile
include $(HTSPREFIX)htscodecs_bundled.mk
# Compiler probe results, generated by ./hts_probe_cc.sh
HTS_HAVE_CPUID =
HTS_BUILD_SSE4 =
HTS_BUILD_AVX2 =
HTS_BUILD_AVX512 =
