#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* .C calls */
extern void reg(void *);

/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP C_gtf2db(SEXP);

static const R_CMethodDef CEntries[] = {
    {"reg", (DL_FUNC) &reg, 1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

static const R_CallMethodDef CallEntries[] = {
    {"C_gtf2db", (DL_FUNC) &C_gtf2db, 1},
    {NULL, NULL, 0}
};

void R_init_SQthesis(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
