bedanno <- function(chr = NULL, start = NULL, end = NULL, strand = NULL, gtf = NULL, upstream = 1000, downstream = 1000)
{
  sl <- .Call("anno_bed", chr, start, end, strand, gtf, upstream, downstream)
  sl
}
#' @title annoBED
#' @description Annotate gene name for bed region. Before annotation you should run ParseBED to parse chr, start and end position from feature name.
#' @param object Seurat object.
#' @param gtf GTF database object, generated by gtf2db().
#' @param assay working assay
#' @return Annotated Seurat object
#' @export
annoBED <- function(object = NULL, gtf = NULL, assay = NULL)
{
  if (notGTF(gtf)) stop("GTF is not specific, use gtf2db load GTF file first.")
  
  assay <- assay %||% DefaultAssay(object)
  old.assay <- DefaultAssay(object)
  DefaultAssay(object) <- assay

  df <- object[[assay]][[]]
  
  if (length(intersect(c("chr","start","end","strand"), colnames(df))) != 4) {
    message("Parse names ..")
    object <- ParseBED(object)
    df <- object[[assay]][[]]
  }

  df0 <- bedanno(chr=df$chr, start=as.integer(df$start), end=df$end, strand = df$strand, gtf=gtf)

  object[[assay]][["gene_name"]] <- df0[[1]]
  object[[assay]][["type"]] <- df0[[2]]

  DefaultAssay(object) <- old.assay
  object
}
