#' @importFrom data.table fread
#' @importFrom Matrix sparseMatrix
.ReadMM <- function(file = NULL)
{
  DT <- fread(file,sep='\t', skip = "%", header = FALSE)
  nr <- DT[1,1]
  nc <- DT[1,2]
  DT <- DT[-1,]
  nr <- nr[[1]]
  nc <- nc[[1]]
  mt <- sparseMatrix(i = DT$V1, j = DT$V2, x = DT$V3, dims = c(nr,nc))

  mt
}
#' @title ReadPISA
#' @description Read feature count matrix generated by `PISA count`.
#' @param mex_dir Feature count outdir generated by `PISA count`.
#' @param prefix Prefix to cell names.
#' @param suffix Suffixed to cell names.
#' @param cells Vector for candidate cells. If not set, will read all cells.
#' @param barcode.path Manually specify barcode path in MEX directory.
#' @param feature.path Manually specify feature path in MEX directory.
#' @param matrix.path Manually specify matrix path in MEX directory.
#' @param peak.path Manually specific peak path (if feature is a region) in MEX directory.
#' @param spliced.path Manually specific spliced matrix path in MEX directory. The spliced, unspliced and spanning read count matrix generated by `PISA count -velo`.
#' @param unspliced.path Manually specific unspliced matrix path.
#' @param spanning.path  Manually specific spanning matrix path.
#' @param use_10X Set TRUE if feature name in the second column of feature file.
#' @param spatial Set TRUE if barcode is coordinate of bin. Will combine x and y coordinate into bin name "x_y".
#' @return Returns a sparse matrix of feature counts or a list of spliced, unspliced, and spanning reads sparse matrix.
#' @importFrom data.table fread
#' @import R.utils
#' @export
ReadPISA <- function(mex_dir=NULL,
                     prefix=NULL,
                     suffix=NULL,
                     cells=NULL,
                     barcode.path = NULL,
                     feature.path = NULL,
                     matrix.path=NULL,
                     peak.path=NULL,
                     spliced.path=NULL,
                     unspliced.path=NULL,
                     spanning.path=NULL,
                     use_10X=FALSE,
                     spatial=FALSE
                     ) {

  if (is.null(mex_dir) && is.null(barcode.path)  && is.null(feature.path) &&
        is.null(matrix.path)) {
    stop("No matrix set.")
  }
  if (!is.null(mex_dir) && !file.exists(mex_dir) ) {
    stop(paste0(mex_dir, " does not exist."))
  }
  if (is.null(barcode.path)) {
    barcode.path <- paste0(mex_dir, "/barcodes.tsv.gz")
  }
  if (is.null(feature.path)) {
    feature.path <- paste0(mex_dir, "/features.tsv.gz")
  }
  if (is.null(matrix.path)) {
    matrix.path <- paste0(mex_dir, "/matrix.mtx.gz")
  }
  if (is.null(peak.path)) {
    peak.path <- paste0(mex_dir, "/peaks.bed.gz")
  }
  if (is.null(spliced.path)) {
    spliced.path <- paste0(mex_dir, "/spliced.mtx.gz")
  }
  if (is.null(unspliced.path)) {
    unspliced.path <- paste0(mex_dir, "/unspliced.mtx.gz")
  }
  if (is.null(spanning.path)) {
    spanning.path <- paste0(mex_dir, "/spanning.mtx.gz")
  }
  if (!file.exists(barcode.path)){
    stop(paste0("No barcode file found at ", mex_dir))
  }

  .renameMatrix <- function(mat, prefix = NULL, suffix = NULL, cells = NULL) {
    if (!is.null(prefix)) {
      colnames(mat) <- paste0(prefix, colnames(mat))      
    }

    if (!is.null(suffix)) {
      colnames(mat) <- paste0(colnames(mat), suffix)
    }
    if (!is.null(cells)) {
      cells <- intersect(cells, colnames(mat))
      mat <- mat[,cells]
    }
    mat
  }
  .ReadPISA1 <- function(barcode.path, peak.path, matrix.path, prefix, suffix, cells) {
    mat <- .ReadMM(file = matrix.path)
    temp <- read.delim(peak.path, header = FALSE)
    feature.names <- paste0(temp$V1, ":", temp$V2, "-", temp$V3)
    barcode.names <- read.delim(barcode.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    colnames(mat) <- barcode.names$V1
    rownames(mat) <- make.unique(feature.names)
   
    .renameMatrix(mat, prefix = prefix, suffix = suffix, cells = cells)
  }
  
  if (!file.exists(feature.path)) {
    message("Load peaks X cells matrix ...")
    if (file.exists(peak.path)) {
      return(.ReadPISA1(barcode.path, peak.path, matrix.path, prefix, suffix, cells))
    } else {
      stop(paste0("No feature file found at ", mex_dir))
    }
  }
  
  .ReadPISA0 <- function(barcode.path, feature.path, matrix.path, use_10X, spatial, prefix, suffix, cells) {
    mat <- .ReadMM(file = matrix.path)
    feature.names <- read.delim(feature.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    barcode.names <- read.delim(barcode.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    if (isTRUE(spatial)) {
      colnames(mat) <- paste(barcode.names$V1, barcode.names$V2, sep="_")
    } else {
      colnames(mat) <- barcode.names$V1
    }
    if (use_10X == TRUE) {
      rownames(mat) <- make.unique(feature.names$V2)
    } else {
      rownames(mat) <- make.unique(feature.names$V1)
    }

    .renameMatrix(mat, prefix = prefix, suffix = suffix, cells = cells)
  }
  
  if (!file.exists(spliced.path) && file.exists(matrix.path)) {
    return(.ReadPISA0(barcode.path, feature.path, matrix.path, use_10X, spatial, prefix, suffix, cells))
  }
  mat <- list()
  cat("Load spliced matrix ...\n")
  mat$spliced <- .ReadMM(file = spliced.path)
  cat("Load unspliced matrix ...\n")
  mat$unspliced <- .ReadMM(file = unspliced.path)

  if (file.exists(spanning.path)) {
    cat("Load spanning matrix ...\n")
    mat$spanning <- .ReadMM(file = spanning.path)
  } else {
    cat("Spanning matrix is null.\n")
  }

  feature.names <- read.delim(feature.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
  )
  barcode.names <- read.delim(barcode.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
                              )
  if (isTRUE(spatial)) {
    colnames(mat$spliced) <- paste(barcode.names$V1, barcode.names$V2, sep="_")
  } else {
    colnames(mat$spliced) <- barcode.names$V1
  }
  rownames(mat$spliced) <- make.unique(feature.names$V1)
  colnames(mat$unspliced) <- barcode.names$V1
  rownames(mat$unspliced) <- make.unique(feature.names$V1)

  mat$spliced <- .renameMatrix(mat$spliced, prefix, suffix, cells)
  mat$unspliced <- .renameMatrix(mat$unspliced, prefix, suffix, cells)
  if (file.exists(spanning.path)) {
    colnames(mat$spanning) <- barcode.names$V1
    rownames(mat$spanning) <- make.unique(feature.names$V1)
    mat$spanning <- .renameMatrix(mat$spanning, prefix, suffix, cells)
  }
  
  if (isTRUE(spatial)) {
    tab  <- data.frame(x = as.integer(barcode.names$V1), y = as.integer(barcode.names$V2))
    mat$dim <- tab
  }
  
  mat
}

#' @export
ReadStereoseq <- function(count = NULL, bin = 50) {
  mtx.file <- paste0(count,"/matrix.mtx.gz")
  feature.file<- paste0(count,"/features.tsv.gz")
  coor.file <- paste0(count,"/barcodes.tsv.gz")
  DT <- fread(mtx.file,sep='\t', skip = "%", header = FALSE)
  feature <- fread(feature.file, sep='\t', header = FALSE)
  coor <- fread(coor.file,sep='\t', header = FALSE)
  nr <- DT[1,1]
  nc <- DT[1,2]
  DT <- DT[-1,]
  nr <- nr[[1]]
  nc <- nc[[1]]
  bin.nm <- paste0(as.integer(coor$V1/bin), "_", as.integer(coor$V2/bin))
  nm <- unique(bin.nm)
  idx <- match(bin.nm, nm)
  mt <- sparseMatrix(i = DT$V1, j = idx[DT$V2], x = DT$V3, dims = c(nr,length(nm)))
  rm(DT)
  colnames(mt) <- nm
  rownames(mt) <- feature$V1
  return(mt)
}
