#' Read feature count matrix generated by `PISA count`.
#'
#' This function will read Matrix Market files from a directory which generated by `PISA count`.
#'
#' @param mex_dir Feature count outdir generated by `PISA count`.
#' @return Returns a sparse matrix of feature counts or a list of spliced, unspliced, and
#'         spanning reads sparse matrix.
#' @importFrom S4Vectors SimpleList
#' @export
ReadPISA <- function(mex_dir=NULL,
                     barcode.path = NULL,
                     feature.path = NULL,
                     matrix.path=NULL,
                     peak.path=NULL,
                     spliced.path=NULL,
                     unspliced.path=NULL,
                     spanning.path=NULL,
                     antisense.path=NULL,
                     use_10X=FALSE,
                     spatial=FALSE
                     ) {

  if (is.null(mex_dir) && is.null(barcode.path)  && is.null(feature.path) &&
        is.null(matrix.path)) {
    stop("No matrix set.")
  }
  if (!is.null(mex_dir) && !file.exists(mex_dir) ) {
    stop(paste0(mex_dir, " does not exist."))
  }
  if (is.null(barcode.path)) {
    barcode.path <- paste0(mex_dir, "/barcodes.tsv.gz")
  }
  if (is.null(feature.path)) {
    feature.path <- paste0(mex_dir, "/features.tsv.gz")
  }
  if (is.null(matrix.path)) {
    matrix.path <- paste0(mex_dir, "/matrix.mtx.gz")
  }
  if (is.null(peak.path)) {
    peak.path <- paste0(mex_dir, "/peaks.bed.gz")
  }
  if (is.null(spliced.path)) {
    spliced.path <- paste0(mex_dir, "/spliced.mtx.gz")
  }
  if (is.null(unspliced.path)) {
    unspliced.path <- paste0(mex_dir, "/unspliced.mtx.gz")
  }
  if (is.null(spanning.path)) {
    spanning.path <- paste0(mex_dir, "/spanning.mtx.gz")
  }
  if (is.null(antisense.path)) {
    antisense.path <- paste0(mex_dir, "/antisense.mtx.gz")
  }
  if (!file.exists(barcode.path)){
    stop(paste0("No barcode file found at ", mex_dir))
  }

  
  .ReadPISA1 <- function(barcode.path, peak.path, matrix.path) {
    mat <- Matrix::readMM(file = matrix.path)
    temp <- read.delim(peak.path, header = FALSE)
    feature.names <- paste0(temp$V1, ":", temp$V2, "-", temp$V3)
    barcode.names <- read.delim(barcode.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    colnames(mat) <- barcode.names$V1
    rownames(mat) <- make.unique(feature.names)
   
    mat
  }
  
  if (!file.exists(feature.path)) {
    message("Load peaks X cells matrix ...")
    if (file.exists(peak.path)) {
      return(.ReadPISA1(barcode.path, peak.path, matrix.path))
    } else {
      stop(paste0("No feature file found at ", mex_dir))
    }
  }
  
  .ReadPISA0 <- function(barcode.path, feature.path, matrix.path, use_10X, spatial) {
    mat <- Matrix::readMM(file = matrix.path)
    feature.names <- read.delim(feature.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    barcode.names <- read.delim(barcode.path,
                                header = FALSE,
                                stringsAsFactors = FALSE
                                )
    if (isTRUE(spatial)) {
      colnames(mat) <- paste(barcode.names$V1, barcode.names$V2, sep="_")
    } else {
      colnames(mat) <- barcode.names$V1
    }
    if (use_10X == TRUE) {
      rownames(mat) <- make.unique(feature.names$V2)
    } else {
      rownames(mat) <- make.unique(feature.names$V1)
    }
    
    if (isTRUE(spatial)) {
      sce <- SingleCellExperiment(counts = mat)
      tab  <- data.frame(x = as.integer(barcode.names$V1), y = as.integer(barcode.names$V2))
      rownames(tab) <- colnames(sce)
      reducedDim(sce, "X_Spatial")<- tab
      return(sce)
    }
    return(mat)
  }
  
  if (!file.exists(spliced.path) && file.exists(matrix.path)) {
    return(.ReadPISA0(barcode.path, feature.path, matrix.path, use_10X, spatial))
  }
  mat <- SimpleList()
  cat("Load spliced matrix ...\n")
  mat$spliced <- Matrix::readMM(file = spliced.path)
  cat("Load unspliced matrix ...\n")
  mat$unspliced <- Matrix::readMM(file = unspliced.path)

  if (file.exists(spanning.path)) {
    cat("Load spanning matrix ...\n")
    mat$spanning <- Matrix::readMM(file = spanning.path)
  } else {
    cat("Spanning matrix is null.\n")
  }

  if (file.exists(antisense.path)) {
    cat("Load antisense matrix ...\n")
    mat$antisense <- Matrix::readMM(file = antisense.path)
  }

  feature.names <- read.delim(feature.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
  )
  barcode.names <- read.delim(barcode.path,
                              header = FALSE,
                              stringsAsFactors = FALSE
                              )
  if (isTRUE(spatial)) {
    colnames(mat$spliced) <- paste(barcode.names$V1, barcode.names$V2, sep="_")
  } else {
    colnames(mat$spliced) <- barcode.names$V1
  }
  rownames(mat$spliced) <- make.unique(feature.names$V1)
  colnames(mat$unspliced) <- barcode.names$V1
  rownames(mat$unspliced) <- make.unique(feature.names$V1)
  if (file.exists(spanning.path)) {
    colnames(mat$spanning) <- barcode.names$V1
    rownames(mat$spanning) <- make.unique(feature.names$V1)
  }
  if (file.exists(antisense.path)) {
    colnames(mat$antisense) <- barcode.names$V1
    rownames(mat$antisense) <- make.unique(feature.names$V1)
  }
  
  if (isTRUE(spatial)) {
    tab  <- data.frame(x = as.integer(barcode.names$V1), y = as.integer(barcode.names$V2))
    rownames(tab) <- colnames(sce)
    #reducedDim(sce, "X_Spatial")<- tab
    mat$dim <- tab
  }

  mat
  #sce <- SingleCellExperiment(mat)
  #sce
}

