#' @name RunLeeScore
#' @title Perform Lee score test for features and test features in parallel. This function used to select co-expressed features on single cell space.
#' @param object Seurat object.
#' @param features Vector of features to calculate.
#' @param assay Name of assay for features. If features not found in default assay, will automatically check other assays.
#' @param test.features Vector of features to compare. Default is AutoCorrFeatures(object, assay = test.assay).
#' @param test.assay Name of assay for test.features. Default is current actived assay.
#' @param layer Which layer to extract data. Default is 'data' layer. So will check if the assay and test.assay are normlised first.
#' @param weight.matrix.name Weight matrix name, this matrix (graph) generated by \code{\link{RunAutoCorr}}.
#' @param perm Permutations for evaluating mean and sd of L score. Default is 100.
#' @param threads Threads. Default is 0, will auto check the CPU cores and set threads = number of CPU cores -1.
#' @export
RunLeeScore <- function(object = NULL, features = NULL, assay = NULL,
                        test.features = NULL,
                        test.assay = NULL,                        
                        layer = "data",
                        weight.matrix.name = "WeightMatrix",
                        perm = 100, threads = 0,
                        seed.use = 999)
{  
  if (is.null(features)) {
    stop("No features specified.")
  }
  if (weight.matrix.name %ni% names(object)) {
    stop("No weight matrix found. Run RunAutoCorr first.")
  }
  old.assay <- DefaultAssay(object)
  assay <- assay %||% DefaultAssay(object)
  test.assay <- test.assay %||% DefaultAssay(object)

  DefaultAssay(object) <- assay
  features <- intersect(features, rownames(object))

  if (is.null(features)) {
    stop("No features found.")
  }

  W <- object[[weight.matrix.name]]

  dat <- FetchData(object, layer = layer, vars = features)
  dat <- t(as.sparse(dat))
  
  DefaultAssay(object) <- test.assay
  test.features <- test.features %||% AutoCorrFeatures(object, assay = test.assay)

  if (is.null(test.features)) {
    stop("No test.features found. Run AutoCorrFeatures(object, assay = test.assay) first.")
  }

  test.features <- intersect(test.features, rownames(object))
  dat1 <- FetchData(object, layer = layer, vars = test.features)
  dat1 <- t(as.sparse(dat1))
  
  threads <- getCores(threads)

  df <- .Call("lee_score", dat, dat1, W, perm, threads, seed.use)
  DefaultAssay(object) <- old.assay

  df <- data.frame(feature = rownames(dat)[df[[1]]],
                   test.feature = rownames(dat1)[df[[2]]],
                   L.score = df[[3]],
                   t = df[[4]])

  # feature, test.feature, L, p, p_adj
  df
}
